services:

  mongo:
    image: mongo:7
    container_name: campaign_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: campaign_backend
    restart: always
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/campaign-db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: campaign_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
